DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Departments;

CREATE TABLE Departments (
  departmentId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT NULL,
  city VARCHAR(64) DEFAULT NULL,
  UNIQUE (name, city)
);

CREATE TABLE Employees (
  employeeId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(512) NOT NULL,
  departmentId INT DEFAULT NULL,
  bossId INT DEFAULT NULL,
  firstName VARCHAR(256) NOT NULL,
  lastName VARCHAR(256) NOT NULL,
  salary DOUBLE DEFAULT 2000,
  FOREIGN KEY (departmentId) REFERENCES Departments (departmentId) ON DELETE RESTRICT,
  FOREIGN KEY (bossId) REFERENCES Employees (employeeId),
  CONSTRAINT validSalary CHECK (salary > 0)
);